# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: ko

pipeline:
# No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# If you'd like to customize it, uncomment and adjust the pipeline.
# See https://rasa.com/docs/rasa/tuning-your-model for more information.
  - name: SpacyNLP
    model: "ko_core_news_sm"
  - name: custom_tokenizer
  - name: RegexFeaturizer
#  - name: LanguageModelFeaturizer
#    model_name: "bert"
#    model_weights: "rasa/LaBSE"
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
  # NLU 대체, 2단계 폴백
  # NLU Fallback-1, Two-Stage Fallback-1  NLU 신뢰도가 낮은 수신 메시지를 처리하려면 FallbackClassifier 를 사용하세요
  - name: FallbackClassifier
    threshold: 0.9
    fallback_action: "action_default_fallback"
    ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
- name: MemoizationPolicy
# 낮은 작업 신뢰도 처리
# Handling Low Action Confidence-1. 구성 업데이트
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: true
#  restrict_rules: true
#  check_for_contradictions: true
#- name: RulePolicy
- name: FormPolicy
- name: UnexpecTEDIntentPolicy
  max_history: 5
  epochs: 100
- name: TEDPolicy
  max_history: 5
  epochs: 100
  constrain_similarities: true
#  model_confidence: softmax

#recipe: default.v1